"""fiv0.3

Revision ID: 3b7dd9ee4338
Revises: 
Create Date: 2018-06-29 11:50:39.965607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b7dd9ee4338'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drug',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drug_name'), 'drug', ['name'], unique=True)
    op.create_table('hospital',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospital_name'), 'hospital', ['name'], unique=True)
    op.create_table('occupation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('operative_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('posture', sa.String(), nullable=True),
    sa.Column('iv_therapy', sa.String(), nullable=True),
    sa.Column('skin', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('reflexes', sa.String(), nullable=True),
    sa.Column('blood_pressure', sa.String(), nullable=True),
    sa.Column('pulse_rate', sa.String(), nullable=True),
    sa.Column('abnormal_reactions', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('national_id', sa.String(length=30), nullable=False),
    sa.Column('first_names', sa.String(length=64), nullable=True),
    sa.Column('surname', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_details_national_id'), 'patient_details', ['national_id'], unique=True)
    op.create_table('post_operative_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instructions_to_ward', sa.String(), nullable=True),
    sa.Column('iv_therapy', sa.String(), nullable=True),
    sa.Column('sedation', sa.String(), nullable=True),
    sa.Column('complications', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pre_operative_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mass', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('pulse', sa.String(), nullable=True),
    sa.Column('respiration', sa.String(), nullable=True),
    sa.Column('respiratory_system', sa.String(), nullable=True),
    sa.Column('cadiovascular_system', sa.String(), nullable=True),
    sa.Column('urine', sa.String(), nullable=True),
    sa.Column('blood_group', sa.String(), nullable=True),
    sa.Column('blood_pressure', sa.String(), nullable=True),
    sa.Column('haemoglobin', sa.String(), nullable=True),
    sa.Column('blood_urea', sa.String(), nullable=True),
    sa.Column('drug_therapy', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('technique',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technique_name'), 'technique', ['name'], unique=True)
    op.create_table('anaesthetic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('drug_id', sa.Integer(), nullable=True),
    sa.Column('technique_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['drug_id'], ['drug.id'], ),
    sa.ForeignKeyConstraint(['technique_id'], ['technique.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=120), nullable=True),
    sa.Column('file_type', sa.String(length=6), nullable=True),
    sa.Column('pre_operative_record_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pre_operative_record_id'], ['pre_operative_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('practitioner_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_names', sa.String(length=64), nullable=True),
    sa.Column('surname', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.Column('occupation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['occupation_id'], ['occupation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_practitioner_details_surname'), 'practitioner_details', ['surname'], unique=False)
    op.create_table('ward',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ward_name'), 'ward', ['name'], unique=False)
    op.create_table('prescription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ordered_by', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ordered_by'], ['practitioner_details.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referer_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_details.id'], ),
    sa.ForeignKeyConstraint(['referer_id'], ['practitioner_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('theater',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('ward_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ward_id'], ['ward.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_theater_name'), 'theater', ['name'], unique=False)
    op.create_table('operation_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('theater_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('pre_operative_record_id', sa.Integer(), nullable=True),
    sa.Column('operative_record_id', sa.Integer(), nullable=True),
    sa.Column('post_operative_record_id', sa.Integer(), nullable=True),
    sa.Column('anaesthetic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['anaesthetic_id'], ['anaesthetic.id'], ),
    sa.ForeignKeyConstraint(['operative_record_id'], ['operative_record.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_details.id'], ),
    sa.ForeignKeyConstraint(['post_operative_record_id'], ['post_operative_record.id'], ),
    sa.ForeignKeyConstraint(['pre_operative_record_id'], ['pre_operative_record.id'], ),
    sa.ForeignKeyConstraint(['reference_id'], ['referal.id'], ),
    sa.ForeignKeyConstraint(['theater_id'], ['theater.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('premedication_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prescription_id', sa.Integer(), nullable=True),
    sa.Column('time_given', sa.Time(), nullable=True),
    sa.Column('given_by', sa.Integer(), nullable=True),
    sa.Column('pre_operative_record_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['given_by'], ['practitioner_details.id'], ),
    sa.ForeignKeyConstraint(['pre_operative_record_id'], ['pre_operative_record.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('surgical_team',
    sa.Column('practioner_id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['operation_record.id'], ),
    sa.ForeignKeyConstraint(['practioner_id'], ['practitioner_details.id'], ),
    sa.PrimaryKeyConstraint('practioner_id', 'operation_id')
    )
    op.create_table('vitals_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('heart_rate', sa.String(), nullable=True),
    sa.Column('oxygen', sa.String(), nullable=True),
    sa.Column('blood_pressure', sa.String(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('operation_record_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['operation_record_id'], ['operation_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vitals_record')
    op.drop_table('surgical_team')
    op.drop_table('premedication_record')
    op.drop_table('operation_record')
    op.drop_index(op.f('ix_theater_name'), table_name='theater')
    op.drop_table('theater')
    op.drop_table('referal')
    op.drop_table('prescription')
    op.drop_index(op.f('ix_ward_name'), table_name='ward')
    op.drop_table('ward')
    op.drop_index(op.f('ix_practitioner_details_surname'), table_name='practitioner_details')
    op.drop_table('practitioner_details')
    op.drop_table('attachment')
    op.drop_table('anaesthetic')
    op.drop_index(op.f('ix_technique_name'), table_name='technique')
    op.drop_table('technique')
    op.drop_table('pre_operative_record')
    op.drop_table('post_operative_record')
    op.drop_index(op.f('ix_patient_details_national_id'), table_name='patient_details')
    op.drop_table('patient_details')
    op.drop_table('operative_record')
    op.drop_table('occupation')
    op.drop_index(op.f('ix_hospital_name'), table_name='hospital')
    op.drop_table('hospital')
    op.drop_index(op.f('ix_drug_name'), table_name='drug')
    op.drop_table('drug')
    # ### end Alembic commands ###
