"""empty message

Revision ID: 4b744d67607d
Revises: c770b3812ef8
Create Date: 2018-07-18 15:16:04.181720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b744d67607d'
down_revision = 'c770b3812ef8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation_record', sa.Column('name', sa.String(length=100), nullable=True))
    op.alter_column('theater', 'ward_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ward', 'hospital_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ward', 'hospital_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('theater', 'ward_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('operation_record', 'name')
    # ### end Alembic commands ###
